/**
 * Libertad - Core Constants & Single Source of Truth
 * Shared configuration schema, presets, and toggle keys across Service Worker, Content Scripts, and Popup.
 */

const TOGGLE_KEYS = [
  // Focus Shield (Macro Distraction Blockers)
  'hideHomeFeed',
  'hideSidebar',
  'hideComments',
  'hideShorts',
  'hideEndScreens',
  // UI Cleaner: Header & Search
  'hideVoiceSearch',
  'hideCreateButton',
  'hideNotifications',
  'hideSearchSuggestions',
  'hideFilterChips',
  // UI Cleaner: Player Controls & Overlays
  'hideAutoplay',
  'hideUpNext',
  'hideWatermark',
  'hidePaidPromo',
  'hideMiniplayer',
  // UI Cleaner: Action Bar & Social
  'hideAskAi',
  'hideDownload',
  'hideThanksClips',
  'hideJoinButton',
  'hideShare',
  'hideSave',
  'hideLikeDislike',
  'hideSubscribeButton',
  'hideSubscriberCount',
  'hideViewsDate',
  'hideMoreActions',
  // UI Cleaner: Feeds & Navigation
  'hideMerchShelf',
  'hideLiveChat',
  'hideTrending',
  'hideMoreFromYoutube',
];

const DEFAULT_SETTINGS = {
  preset: 'balanced', // 'off', 'basic', 'balanced', 'extreme', 'custom'
  theme: 'dark', // 'dark', 'light', 'oled'
  lang: 'auto', // 'auto', 'en', 'es'
  scale: 'auto', // 'auto', '100', '120', '140'
  activeTab: 'focus', // 'focus', 'cleaner', 'extras'
  hideHomeFeed: false,
  hideSidebar: true,
  hideComments: true,
  hideShorts: true,
  hideEndScreens: true,
  // Cleaner: Header & Search
  hideVoiceSearch: true,
  hideCreateButton: true,
  hideNotifications: true,
  hideSearchSuggestions: false,
  hideFilterChips: false,
  // Cleaner: Player & Overlays
  hideAutoplay: true,
  hideUpNext: true,
  hideWatermark: true,
  hidePaidPromo: true,
  hideMiniplayer: true,
  // Cleaner: Action Bar & Social
  hideAskAi: true,
  hideDownload: true,
  hideThanksClips: true,
  hideJoinButton: true,
  hideShare: false,
  hideSave: false,
  hideLikeDislike: false,
  hideSubscribeButton: false,
  hideSubscriberCount: false,
  hideViewsDate: false,
  hideMoreActions: false,
  // Cleaner: Feeds & Navigation
  hideMerchShelf: true,
  hideLiveChat: true,
  hideTrending: true,
  hideMoreFromYoutube: true,
  // Power Modules
  showDislikes: true,
  untranslateTitles: true,
  customConfig: {
    hideHomeFeed: false,
    hideSidebar: true,
    hideComments: true,
    hideShorts: true,
    hideEndScreens: true,
    hideVoiceSearch: true,
    hideCreateButton: true,
    hideNotifications: true,
    hideSearchSuggestions: false,
    hideFilterChips: false,
    hideAutoplay: true,
    hideUpNext: true,
    hideWatermark: true,
    hidePaidPromo: true,
    hideMiniplayer: true,
    hideAskAi: true,
    hideDownload: true,
    hideThanksClips: true,
    hideJoinButton: true,
    hideShare: false,
    hideSave: false,
    hideLikeDislike: false,
    hideSubscribeButton: false,
    hideSubscriberCount: false,
    hideViewsDate: false,
    hideMoreActions: false,
    hideMerchShelf: true,
    hideLiveChat: true,
    hideTrending: true,
    hideMoreFromYoutube: true,
  },
};

const PRESET_MAP = {
  off: {
    hideHomeFeed: false,
    hideSidebar: false,
    hideComments: false,
    hideShorts: false,
    hideEndScreens: false,
    hideVoiceSearch: false,
    hideCreateButton: false,
    hideNotifications: false,
    hideSearchSuggestions: false,
    hideFilterChips: false,
    hideAutoplay: false,
    hideUpNext: false,
    hideWatermark: false,
    hidePaidPromo: false,
    hideMiniplayer: false,
    hideAskAi: false,
    hideDownload: false,
    hideThanksClips: false,
    hideJoinButton: false,
    hideShare: false,
    hideSave: false,
    hideLikeDislike: false,
    hideSubscribeButton: false,
    hideSubscriberCount: false,
    hideViewsDate: false,
    hideMoreActions: false,
    hideMerchShelf: false,
    hideLiveChat: false,
    hideTrending: false,
    hideMoreFromYoutube: false,
    descKey: 'descOff',
  },
  basic: {
    hideHomeFeed: false,
    hideSidebar: false,
    hideComments: true,
    hideShorts: false,
    hideEndScreens: true,
    hideVoiceSearch: false,
    hideCreateButton: false,
    hideNotifications: false,
    hideSearchSuggestions: false,
    hideFilterChips: false,
    hideAutoplay: false,
    hideUpNext: true,
    hideWatermark: true,
    hidePaidPromo: true,
    hideMiniplayer: false,
    hideAskAi: true,
    hideDownload: true,
    hideThanksClips: false,
    hideJoinButton: false,
    hideShare: false,
    hideSave: false,
    hideLikeDislike: false,
    hideSubscribeButton: false,
    hideSubscriberCount: false,
    hideViewsDate: false,
    hideMoreActions: false,
    hideMerchShelf: true,
    hideLiveChat: false,
    hideTrending: false,
    hideMoreFromYoutube: false,
    descKey: 'descBasic',
  },
  balanced: {
    hideHomeFeed: false,
    hideSidebar: true,
    hideComments: true,
    hideShorts: true,
    hideEndScreens: true,
    hideVoiceSearch: true,
    hideCreateButton: true,
    hideNotifications: true,
    hideSearchSuggestions: false,
    hideFilterChips: false,
    hideAutoplay: true,
    hideUpNext: true,
    hideWatermark: true,
    hidePaidPromo: true,
    hideMiniplayer: true,
    hideAskAi: true,
    hideDownload: true,
    hideThanksClips: true,
    hideJoinButton: true,
    hideShare: false,
    hideSave: false,
    hideLikeDislike: false,
    hideSubscribeButton: false,
    hideSubscriberCount: false,
    hideViewsDate: false,
    hideMoreActions: false,
    hideMerchShelf: true,
    hideLiveChat: true,
    hideTrending: true,
    hideMoreFromYoutube: true,
    descKey: 'descBalanced',
  },
  extreme: {
    hideHomeFeed: true,
    hideSidebar: true,
    hideComments: true,
    hideShorts: true,
    hideEndScreens: true,
    hideVoiceSearch: true,
    hideCreateButton: true,
    hideNotifications: true,
    hideSearchSuggestions: true,
    hideFilterChips: true,
    hideAutoplay: true,
    hideUpNext: true,
    hideWatermark: true,
    hidePaidPromo: true,
    hideMiniplayer: true,
    hideAskAi: true,
    hideDownload: true,
    hideThanksClips: true,
    hideJoinButton: true,
    hideShare: true,
    hideSave: true,
    hideLikeDislike: true,
    hideSubscribeButton: true,
    hideSubscriberCount: true,
    hideViewsDate: true,
    hideMoreActions: true,
    hideMerchShelf: true,
    hideLiveChat: true,
    hideTrending: true,
    hideMoreFromYoutube: true,
    descKey: 'descExtreme',
  },
  custom: {
    descKey: 'descCustom',
  },
};

if (typeof globalThis !== 'undefined') {
  globalThis.TOGGLE_KEYS = TOGGLE_KEYS;
  globalThis.DEFAULT_SETTINGS = DEFAULT_SETTINGS;
  globalThis.PRESET_MAP = PRESET_MAP;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TOGGLE_KEYS, DEFAULT_SETTINGS, PRESET_MAP };
}
